name: tests

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: build
      run: |
        cd third-party/gtest && git checkout release-1.11.0 && cd ../..
        cmake -H. -B_build -DBUILD_TESTS=ON
        cmake --build _build
      
    - name: tests
      run: _build/check
