name: tests

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: build
      run: |
        echo LS 1
        ls
        echo LS 2
        ls third-party
        echo LS 3
        ls third-party/gtest
        cmake -H. -B_build -DBUILD_TESTS=ON
        cmake --build _build
      
    - name: tests
      run: _build/check
